version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/GoodVibes:cached
    command: sleep infinity
    network_mode: service:mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/goodvibes
      - DB_NAME=goodvibes

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb-data:
